# Generated by Django 2.2.6 on 2021-02-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210203_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Напишите,чем вы хотите поделиться', verbose_name='Текст'),
        ),
    ]
