# Generated by Django 2.2.6 on 2021-02-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210211_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите файл изображения', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
